### PR TITLE
CSS improvements

### PR DESCRIPTION
**Pull request by cherkesky**
Edited the CSS files for extra coolness

To check, do the following:
1) In your terminal (and possibly in your project directory), do git fetch --all
2) Then git checkout gc-css
3) In your terminal, connect to the server with hs
4) Using your browser, ensure the links work

### CODE REVIEW

**Comment by laurenriddle** [comment]
looks good!!

**Comment by schatfield** [comment]
lookin' pretty cool! :)

**Comment by rhc822** [comment]
Thank you Guy, looks good

**Comment by cherkesky** [comment]
Thank you guys. im meging it to master then.

**Pull request merged**
