### PR TITLE
News feed

### PR DESCRIPTION
**Pull request by rhc822**
I completed the News Feed section. To check, do the following:
1) In your terminal (and possibly in your project directory), do `git fetch --all`
2) Then `git checkout theirBranch`
3) In your terminal, connect to the server with hs
4) Using your browser, ensure it works

### CODE REVIEW

**Comment by laurenriddle** [comment]
Looks great, except for the /Users/ryan/workspace/luckylanding_typhoons/celebrity-tribute-luckylanding-typhoons/news_feed/celebrity_tribute_news_feed_1.png at the bottom of the page.

**Comment by schatfield** [comment]
looks good! only fix needed is the users/ryan/workspace... link mentioned by Lauren above.

**Comment by schatfield** [comment]
changes are perfecto!

**Comment by cherkesky** [comment]
good to go!

**Comment by laurenriddle** [comment]
Looks great!!

**Pull request merged**
