### PR TITLE
Lr personal

### PR DESCRIPTION
**Pull request by laurenriddle**
Made the Career page. To check, do the following:
1) In your terminal (and possibly in your project directory), do git fetch --all
2) Then git checkout theirBranch
3) In your terminal, connect to the server with hs
4) Using your browser, ensure the links work, and all components on the page look correct.

### CODE REVIEW

**Comment by schatfield** [comment]
I like it!

**Comment by cherkesky** [comment]
good to go! :)

**Comment by laurenriddle** [comment]
Thanks guys!

**Comment by rhc822** [comment]
Brilliant!

**Pull request merged**
