### PR TITLE
Gc personal

### PR DESCRIPTION
**Pull request by cherkesky**
Completed my personal.html file and added an image

. To check, do the following:
1) In your terminal (and possibly in your project directory), do git fetch --all
2) Then git checkout gc-personal
3) In your terminal, connect to the server with hs
4) Using your browser, ensure the links work

### CODE REVIEW

**Comment by schatfield** [comment]
looks awesome!!

**Comment by rhc822** [comment]
Looks great!

**Comment by laurenriddle** [comment]
looks great!!!

**Comment by rhc822** [comment]
I changed my mind, it doesn't look good!

**Comment by rhc822** [comment]
just kidding

**Pull request merged**
