### PR TITLE
Rhc boilerplate html

### PR DESCRIPTION
**Pull request by rhc822**
Made our file structure and each file contains nav, footer, and placeholder body. To check, do the following:

1) In your terminal (and possibly in your project directory), do `git fetch --all`
2) Then `git checkout theirBranch`
3) In your terminal, connect to the server with `hs`
4) Using your browser, ensure the links work

### CODE REVIEW

**Comment by laurenriddle** [comment]
Looks good! Everything works!

**Comment by rhc822** [comment]
> Looks good! Everything works!

Thanks Lauren

**Comment by cherkesky** [comment]
all the links are working. the structure is amazing. I approve

**Comment by rhc822** [comment]
> all the links are working. the structure is amazing. I approve

Thank you Guy, you are very encouraging

**Comment by schatfield** [comment]
sic work ryan!

**Comment by rhc822** [comment]
> sic work ryan!

Yo

**Pull request merged**
